FROM ghcr.io/mlflow/mlflow:v2.11.3

RUN pip install psycopg2-binary boto3 --quiet

RUN python -c "import mlflow.cli as c, inspect; f = inspect.getfile(c); txt = open(f).read(); txt = txt.replace(chr(39)+'127.0.0.1'+chr(39), chr(39)+'0.0.0.0'+chr(39)); open(f,'w').write(txt); print('Patched OK')"
