apiVersion: v1
kind: Service
metadata:
  name: anomaly-api
  namespace: mlops
spec:
  type: NodePort
  selector:
    app: anomaly-api
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30800     # API: $(minikube ip):30800